<!DOCTYPE html>
<html lang="en">
<head>	<title>FV-iSCARdb</title>	<META NAME="Generator" CONTENT="TextPad 4.6">	<META NAME="Author" CONTENT="premkrishnan">	<META NAME="Keywords" CONTENT="iscar, rapd">	<META NAME="Description" CONTENT="Predicted SCAR markers for fruit and vegetables crops">	<link rel="icon" href="images/icon.gif" />	<!--// CSS //-->	<link href="css/bootstrap.min.css" rel="stylesheet">	<link href="css/main.css" rel="stylesheet">		<script type="text/javascript">		function validateForm()		{			var i = document.getElementById("species").value;			if (i=="0")			{				alert("Species name is missing!");				return false;			}			var j = document.getElementById("seqtype").value;			if (j=="0")			{				alert("Sequence type is missing!");				return false;			}						if ((i=="Not known") && (j=="Not known"))			{				alert("You must choose either a Species or a Sequence Type!");				return false;			}					}			</script>	</head>
<body>    <!--========================================           Header    ========================================-->    <!--//** Navigation**//-->    <nav class="navbar navbar-default navbar-fixed white no-background bootsnav navbar-scrollspy" data-minus-value-desktop="70" data-minus-value-mobile="55" data-speed="1000">        <div class="container">            <!-- Start Header Navigation -->            <div class="navbar-header">                <a class="navbar-brand"><img src="images/logo.png" alt="logo"></a>            </div>            <!-- End Header Navigation -->		            <!-- Collect the nav links, forms, and other content for toggling -->            <div class="collapse navbar-collapse" id="navbar-menu">                <ul class="nav navbar-nav navbar-right">                    <li class="active scroll"><a href="#home">Home</a></li>					<li class="active scroll"><a href="credits_page.php">Credits</a></li>                </ul>            </div>            <!-- /.navbar-collapse -->        </div>    </nav>			    <section id="home">        <div class="container">            <div class="row">                <div class="col-md-6">                    <h2>FV-iSCARdb</h2>					<hr />                    <h4>SCAR primer designer tool</h4>                    <p>A software (Marker express 1.0) was developed by us to locate RAPD/ISSR primers & design iSCAR primers. It was validated (PremKrishnan and Arunachalam, 2012) using expressed sequences and published polymorphic RAPD primers  of oil palm. We used the software and mined the complete genome, EST and core nucleotide sequences of apple, banana, straw berry, papaya, cacao, date palm, potato, tomato, melon for RAPD/ISSR priming sites and designed iSCAR (in silico Sequence Characterised and amplified region) markers. We built this database to provide the designed iSCAR primer sequences in the above plants to scientific community.</p>                </div>
                <div class="col-md-5 col-md-offset-1">                    <form id="search" class="signup-form" method="post" action="datatable_final.php" onsubmit="return validateForm();">                        <h1 class="text-center">Search</h1>                        <hr>                        <div class="form-group">						<!-- DROPDOWN LIST AREA START >> PLEASE MODIFY BASED ON YOUR TABLE -->
						<?php
						include('dbconfig.php');						//choose species						
						echo "<select  id='species' name='species' class='ui-autocomplete-input form-control' >";						echo "<option value='0'> - select species -</option>";
						$sqlSP = "select * from species order by SpeciesID"; // FETCH
						$result = $conn->query($sqlSP);						
						while ($row = $result->fetch_assoc())
						{
							unset($id, $name);
							echo "<option value=\"".$row['SpeciesName']."\">".$row['SpeciesName']."</option>";
						}
						echo "</select>";						echo "<br />";						//choose sequence type												echo "<select  id='seqtype' name='seqtype'  class='ui-autocomplete-input form-control' >";						echo "<option value='0'> - select sequence type -</option>";						$sqlST = "select * from seqtype order by SequenceTypeID"; // FETCH						$result = $conn->query($sqlST);						while ($row = $result->fetch_assoc())						{							unset($id, $name);							echo "<option value=\"".$row['SequenceType']."\">".$row['SequenceType']."</option>";						}						echo "</select>";						echo "<br />";						//choose primer												/* echo "<select name='primer'  class='ui-autocomplete-input form-control' >";						echo "<option value='0'> :: select ::</option>";						$sqlP = "select * from primer order by PrimerID"; // FETCH						$result = $conn->query($sqlP);						while ($row = $result->fetch_assoc())						{							unset($id, $name);							echo "<option value=\"".$row['PrimerName']."\">".$row['PrimerName']."</option>";						}						echo "</select>";						echo "<br />";	 */					
						$conn->close();
						?>
						<!-- DROPDOWN LIST AREA END -->
                        <div class="form-group text-center">							<button type="submit" id='submit' name="submit" class="btn btn-blue">Search</button>
                        </div>
                    </form>                </div>            </div>        </div>    </section>   <!--========================================            How to?    ========================================-->    <section id="howto">        <div class="container">            <h3>How to use the tool?</h3>            <div class="row">                <div class="">                        <p>SCAR primer searching is possible for the following combinations:</br>						1. Species + Sequence type</br>						2. Species + Not known (Sequence type not sure)</br>						3. Sequence type + Not known (Species not sure)</br></br>												<h4>Important!</h4>						Both options cannot be <b>"Not known"</b>, means you must choose either a <b>Species</b> or a <b>Sequence type</b>.</p>                </div>            </div>        </div>    </section>    <!--========================================           Footer    ========================================-->    <footer>        <div>            <div align="center">                <div >&copy;2018 All rights reserved</div>            </div>        </div>    </footer>	</body></html>